# This image provides a mongo installation from which to run backups
FROM mongodb/mongodb-community-server:6.0.6-ubi8

# Change timezone to PST for convenience
ENV TZ=PST8PDT

# Set the workdir to be root
WORKDIR /

# Load the backup scripts into the container (must be executable).
COPY backup.* /

# ========================================================================================================
# Install go-crond (from https://github.com/webdevops/go-crond)
#
# CRON Jobs in OpenShift:
#  - https://blog.danman.eu/cron-jobs-in-openshift/
# --------------------------------------------------------------------------------------------------------
ARG SOURCE_REPO=webdevops
ARG GOCROND_VERSION=23.2.0
ADD https://github.com/$SOURCE_REPO/go-crond/releases/download/$GOCROND_VERSION/go-crond.linux.amd64 /usr/bin/go-crond

# COPY backup.conf /conf/backup.conf

# COPY mongod.conf /etc/mongod.conf
# RUN mv /etc/mongod.conf.orig /etc/mongod.conf
# RUN mkdir -p /var/lib/mongo/data
USER root

RUN chmod +x /usr/bin/go-crond
COPY vc-authn-oidc-mongodb-headless-vcauthn_2023-11-02_10-54-08.sql.gz /backups/daily/2023-11-02/vc-authn-oidc-mongodb-headless-vcauthn_2023-11-02_10-54-08.sql.gz
RUN chown 1005420000:1005420000 /data/db
# RUN chown 1005420000:1005420000 /var/lib/mongo
# RUN chown 1005420000:1005420000 /var/log/mongodb
# ========================================================================================================

# ========================================================================================================
# Perform operations that require root privilages here ...
# --------------------------------------------------------------------------------------------------------
RUN echo $TZ > /etc/timezone
# ========================================================================================================

# Important - Reset to the base image's user account.
USER 999

# Set the default CMD.
CMD bash /backup.sh
